ls:
  .dir: regex:\.?[a-z0-9]+(-[a-z0-9]+)*
  .*: regex:[a-z0-9]*([._][a-z0-9]+)*

ignore:
  - .git
  - .direnv
  - result
  - result-*
  - "**/logs"
  - "**/.cache"

  - "**/README.md"
  - "**/AGENTS.md"
  - "**/CLAUDE.md"
  - "**/SKILL.md"

  - _minted*
  - pythontex-files-*
  - svg-inkscape
  - auto
